spring:
  data:
    mongodb:
      #      uri: mongodb://127.0.0.1:27017/shiro
      host: localhost
      port: 27017
      database: security
      username:
      password:
level:
  org:
    springframework:
      data:
        mongodb:
          core: debug
jwt:
  tokenHeader: Authorization #JWT Header
  secret: mySecret #JWT Secret
  expiration: 604800 #JWT Expire(60*60*24)
  tokenHead: Bearer  #JWT Payload