management:
  endpoint:
    auditevents:
      enabled: true
    metrics:
      enabled: true
    heapdump:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, env, info, heapdump, metrics